### ISSUE TITLE
1.20.2 branch is needed 

### ISSUE THREAD

**Issue by minimiscus** [Faithful-Resource-Pack/Faithful-32x-Mods#15]
As per the title, some mod textures have changed their directories to fit the new GUI-separated directories of 1.20.2 like the most recent commit `13316cb`.

**Comment by Pomi108** [comment]
Done; I chose to delete all the assets on the branch and start with a clean slate, but please feel free to make a pull request with existing 1.20.1 textures if they still work in 1.20.2
