### ISSUE TITLE
Download button does not actually provide a working zip because it puts it within a containing folder

### ISSUE THREAD

**Issue by kittywitch** [Faithful-Resource-Pack/Faithful-32x-Mods#39]
Instead of getting a zip where the assets and pack.mcmeta are inside the root of the zip file, you get one in which a folder called "Faithful-32x-Mods-1.20.x" folder contains those items. This means that your instructions do not work and the download system is unusable without repacking the resulting zip!

**Comment by Jamiscus** [comment]
that's just how github zips downloaded files and there isn't anything we can do about that

**Comment by kittywitch** [comment]
hi! your instructions are incorrect then, since they require me to repack the zip by hand.

**Comment by kittywitch** [comment]
consider your README; "Select the desired Minecraft version using the dropdown above, then press the big green Code button and select Download ZIP." it's wrong, since i can't simply put that into the game's resourcepacks folder.

**Comment by Jamiscus** [comment]
that doesn't necessarily mean it's "wrong" per se, just missing an in between step. i may update it

**Comment by kittywitch** [comment]
i hope you do update it! i don't even think it's particularly hard to implement a CI pipeline for zip releases built with a shell script which runs upon any tag from the repo (i did this today, for a modpack project), so it should even be possible *without* having to make every end user commit to doing some kind of workaround.

i... may even try and do this tomorrow and make a PR.

**Comment by Spongman** [comment]
yeah, you should add a note saying "don't actually use the .ZIP you download, you have to unzip it and manually re-construct a working .ZIP yourself."

I expected the downloaded .ZIP to work.

**Comment by minimiscus** [comment]
#41 shall be fixed in like 2 years
